services:
  app:
    build:
      context: .
      dockerfile: resources/docker/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION:-8.4}
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: ${PROJECT_PREFIX:-cli-options-parser}-app
    hostname: ${PROJECT_PREFIX:-cli-options-parser}-app
    working_dir: /srv
    volumes:
      - .:/srv
